# If this is a new installation run the following steps:
# 1. Run `git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm`
# 2. Enter 'tmux'
# 3. Run `tmux source ~/.tmux.conf` or <leader> + 'r'
# 4. With 'tmux' open, run `<C-s + I>` to install plugins
# 5. Exit 'tmux' and re-enter
# 6. Enjoy!

unbind r
bind r source-file ~/.tmux.conf

set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s extended-keys on
set -s extended-keys-format csi-u
set -as terminal-features ',*ghostty*:extkeys'

# set status bar color to dark
set -g status-style 'bg=#333333 fg=#5eacd3'

# pane starts at 1 instead of 0
set -g base-index 1

set -s escape-time 0

# toggle from super-b to super-s
set -g prefix C-s

set -g mouse on

bind w choose-tree -Zs
bind N new-session
# set session default directory to current pane's path
bind a attach-session -t . -c "#{pane_current_path}"

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -n S-Enter send-keys Escape "[13;2u"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# tmux-resurrect custom keybindings (defaults conflict with prefix C-s)
set -g @resurrect-save 'W'
set -g @resurrect-restore 'E'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
